//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRInfo.Resouces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WRInfo.Resouces.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP.
        /// </summary>
        internal static string ability_point {
            get {
                return ResourceManager.GetString("ability_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do respect all players and DO NOT EVER judge any players base on their stat.
        /// </summary>
        internal static string agreement {
            get {
                return ResourceManager.GetString("agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        internal static string api {
            get {
                return ResourceManager.GetString("api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.
        /// </summary>
        internal static string battle_count {
            get {
                return ResourceManager.GetString("battle_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple &gt; Cyan &gt; Green &gt; Yellow &gt; Orange &gt; Red.
        /// </summary>
        internal static string colour_meaning {
            get {
                return ResourceManager.GetString("colour_meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed....
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Version -&gt; .
        /// </summary>
        internal static string curr_version {
            get {
                return ResourceManager.GetString("curr_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Developer).
        /// </summary>
        internal static string developer {
            get {
                return ResourceManager.GetString("developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading personal rating....
        /// </summary>
        internal static string download_pr {
            get {
                return ResourceManager.GetString("download_pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading warship information....
        /// </summary>
        internal static string download_warships {
            get {
                return ResourceManager.GetString("download_warships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste your game path below.
        /// </summary>
        internal static string enter_gamepath {
            get {
                return ResourceManager.GetString("enter_gamepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Enter help to show instructions.
        /// </summary>
        internal static string enter_help {
            get {
                return ResourceManager.GetString("enter_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GamePath.
        /// </summary>
        internal static string gamepath {
            get {
                return ResourceManager.GetString("gamepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey player hides their stat.
        /// </summary>
        internal static string grey_player {
            get {
                return ResourceManager.GetString("grey_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is found -&gt; .
        /// </summary>
        internal static string has_update {
            get {
                return ResourceManager.GetString("has_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Clear console.
        /// </summary>
        internal static string help_clear {
            get {
                return ResourceManager.GetString("help_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Exit WRInfo.
        /// </summary>
        internal static string help_exit {
            get {
                return ResourceManager.GetString("help_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Start World of Warships.
        /// </summary>
        internal static string help_gamestart {
            get {
                return ResourceManager.GetString("help_gamestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Show help (what you are reading now).
        /// </summary>
        internal static string help_help {
            get {
                return ResourceManager.GetString("help_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Change WRInfo language.
        /// </summary>
        internal static string help_language {
            get {
                return ResourceManager.GetString("help_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Show main menu.
        /// </summary>
        internal static string help_menu {
            get {
                return ResourceManager.GetString("help_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Change game path.
        /// </summary>
        internal static string help_path {
            get {
                return ResourceManager.GetString("help_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Reset whole program.
        /// </summary>
        internal static string help_reset {
            get {
                return ResourceManager.GetString("help_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Change WRInfo server and data will be redownloaded.
        /// </summary>
        internal static string help_server {
            get {
                return ResourceManager.GetString("help_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Start real time stat checker.
        /// </summary>
        internal static string help_start {
            get {
                return ResourceManager.GetString("help_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRInfo is an useful tool to help you understand your teammates and opponents. This program will provide statistics for all players. However, if it is a HIDDEN account, no information will be shown..
        /// </summary>
        internal static string introduction {
            get {
                return ResourceManager.GetString("introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is your python.log?.
        /// </summary>
        internal static string no_log {
            get {
                return ResourceManager.GetString("no_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is up to date.
        /// </summary>
        internal static string no_update {
            get {
                return ResourceManager.GetString("no_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your language is not on the list, apologies for that. You are welcomed to submit a pull request for more languages.
        /// </summary>
        internal static string only_threelanguages {
            get {
                return ResourceManager.GetString("only_threelanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this path is not valid. Please enter it again &gt;_&lt;.
        /// </summary>
        internal static string path_notvalid {
            get {
                return ResourceManager.GetString("path_notvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepath is valid ^_^.
        /// </summary>
        internal static string path_valid {
            get {
                return ResourceManager.GetString("path_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string player_name {
            get {
                return ResourceManager.GetString("player_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Rating....
        /// </summary>
        internal static string pr {
            get {
                return ResourceManager.GetString("pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling data from WoWs API....
        /// </summary>
        internal static string pull_api {
            get {
                return ResourceManager.GetString("pull_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input not valid.
        /// </summary>
        internal static string server_notvalid {
            get {
                return ResourceManager.GetString("server_notvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        internal static string ship_name {
            get {
                return ResourceManager.GetString("ship_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for path .
        /// </summary>
        internal static string validate_gamepath {
            get {
                return ResourceManager.GetString("validate_gamepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Websites ---.
        /// </summary>
        internal static string website_link {
            get {
                return ResourceManager.GetString("website_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to WRInfo.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WR.
        /// </summary>
        internal static string win_rate {
            get {
                return ResourceManager.GetString("win_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoWs Info
        ///IOS: https://itunes.apple.com/app/id1202750166
        ///Android: https://play.google.com/store/apps/details?id=com.yihengquan.wowsinfo.
        /// </summary>
        internal static string wows_info {
            get {
                return ResourceManager.GetString("wows_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRInfo.
        /// </summary>
        internal static string wrinfo {
            get {
                return ResourceManager.GetString("wrinfo", resourceCulture);
            }
        }
    }
}
