//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRInfo.Resouces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WRInfo.Resouces.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do respect all players and DO NOT EVER judge any players base on their stat.
        /// </summary>
        internal static string agreement {
            get {
                return ResourceManager.GetString("agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press any key to continue....
        /// </summary>
        internal static string anykey_continue {
            get {
                return ResourceManager.GetString("anykey_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        internal static string api {
            get {
                return ResourceManager.GetString("api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed....
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Version -&gt; .
        /// </summary>
        internal static string curr_version {
            get {
                return ResourceManager.GetString("curr_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading personal rating....
        /// </summary>
        internal static string download_pr {
            get {
                return ResourceManager.GetString("download_pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading warship information....
        /// </summary>
        internal static string download_warships {
            get {
                return ResourceManager.GetString("download_warships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -&gt; fatal error, program will exit.
        /// </summary>
        internal static string fatal_error {
            get {
                return ResourceManager.GetString("fatal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GamePath.
        /// </summary>
        internal static string gamepath {
            get {
                return ResourceManager.GetString("gamepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is found -&gt; .
        /// </summary>
        internal static string has_update {
            get {
                return ResourceManager.GetString("has_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRInfo is an useful tool to help you understand your teammates and opponents. This program will provide statistics for all players. However, if it is a HIDDEN account, no information will be shown..
        /// </summary>
        internal static string introduction {
            get {
                return ResourceManager.GetString("introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is up to date.
        /// </summary>
        internal static string no_update {
            get {
                return ResourceManager.GetString("no_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your language is not on the list, apologies for that. You are welcomed to submit a pull request for more languages.
        /// </summary>
        internal static string only_threelanguages {
            get {
                return ResourceManager.GetString("only_threelanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this path is not valid. Please enter it again &gt;_&lt;.
        /// </summary>
        internal static string path_notvalid {
            get {
                return ResourceManager.GetString("path_notvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepath is valid ^_^.
        /// </summary>
        internal static string path_valid {
            get {
                return ResourceManager.GetString("path_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Rating....
        /// </summary>
        internal static string pr {
            get {
                return ResourceManager.GetString("pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling data from WoWs API....
        /// </summary>
        internal static string pull_api {
            get {
                return ResourceManager.GetString("pull_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input not valid.
        /// </summary>
        internal static string server_notvalid {
            get {
                return ResourceManager.GetString("server_notvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for path .
        /// </summary>
        internal static string validate_gamepath {
            get {
                return ResourceManager.GetString("validate_gamepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to WRInfo.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Rating is measure of skill in World of Warships. It measures performance in every warship and compares it to certain expected values. Differences between actual and expected values are used to calculate final Personal Rating value..
        /// </summary>
        internal static string whatis_pr {
            get {
                return ResourceManager.GetString("whatis_pr", resourceCulture);
            }
        }
    }
}
